<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="RightSetBox.aspx.cs" Inherits="MeetingResMagSys.Pages.RightSetBox" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>系统默认角色权限设置窗</title>
    <script src="../Scripts/jquery.min.js"></script>
    <script src="../Scripts/fancybox2.1.5/jquery.fancybox.js"></script>
    <script src="../Scripts/bootstrap.min.js"></script>
    <link href="../Scripts/fancybox2.1.5/source/jquery.fancybox.css" rel="stylesheet" />
    <link href="../StyleSheet/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <form id="form1" runat="server">
        <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
        <asp:UpdatePanel runat="server" ID="UpdatePanel1">
            <ContentTemplate>
                <div class="breadcrumbs" id="breadcrumbs" style="background-color: #ffffff">
                    <ul class="breadcrumb">
                        <li class="active">
                            <label id="lbRoleName" runat="server">角色权限设置</label>
                        </li>
                    </ul>
                </div>
                <div class="page-content">
                    <div class="row">
                        <div class="col-xs-12">
                            <!-- PAGE CONTENT BEGINS -->
                            <div class="row">
                                <div class="col-xs-4">
                                </div>
                                <div class="col-xs-4 text-center" style="padding-left: 0px; padding-right: 0px;">
                                    <div class="row" style="margin-bottom: 5px; margin-top: 5px;">
                                        <div class="col-xs-12 text-center">
                                            <asp:Button ID="btnSave" runat="server" Text="保存" OnClick="btnSave_Click" class="btn btn-default" />
                                        </div>
                                    </div>
                                    <div class="panel panel-default" style="min-height: 400px;">
                                        <div class="panel-body">
                                            <asp:Panel ID="panelUser" runat="server" ScrollBars="None">
                                                <asp:TreeView ID="TreeView1" runat="server" ExpandDepth="1" ShowLines="true" NodeWrap="True"
                                                    AutoGenerateDataBindings="False" OnTreeNodeCheckChanged="TreeView1_TreeNodeCheckChanged"
                                                    ShowCheckBoxes="All" EnableClientScript="False">
                                                    <NodeStyle NodeSpacing="0px" VerticalPadding="2px" />
                                                    <ParentNodeStyle />
                                                    <SelectedNodeStyle BackColor="#B5B5B5" Font-Underline="False" VerticalPadding="2px" />
                                                </asp:TreeView>
                                            </asp:Panel>
                                        </div>
                                        <asp:HiddenField ID="PanelScroll" runat="server" />
                                    </div>
                                </div>
                            </div>
                            <!-- PAGE CONTENT ENDS -->
                        </div>
                    </div>
                </div>
                <script type="text/javascript">
                    // 点击复选框时触发事件
                    function postBackByObject() {
                        var o = window.event.srcElement;
                        if (o.tagName == "INPUT" && o.type == "checkbox") {
                            __doPostBack("ctl00_MainContent_PanelScroll", "");
                        }
                    }

                    function SetScrollTop(type, panelId, hiddenId) {
                        if (type.toString() == "0") {
                            $("#" + hiddenId).val($("#" + panelId).scrollTop());
                        }
                        else {
                            $("#" + panelId).scrollTop($("#" + hiddenId).val());
                            $("#" + panelId).scrollTop($("#" + hiddenId).val());
                        }
                    }

                    function Refresh() {
                        window.opener.location.href;
                    }
                </script>
            </ContentTemplate>
        </asp:UpdatePanel>
    </form>
</body>
</html>
